float32 accel_longitudinal_mps2  # Longitudinal acceleration in m/s^2 (-64 to 63.998)
float32 accel_lateral_mps2       # Lateral acceleration in m/s^2 (-64 to 63.998)
float32 yaw_rate_degps           # Yaw rate in degrees per second (-256 to 255.992)

# BO_ 1281 AI2LOG_Dynamics2: 6 PCAN
#  SG_ Accel_longitudinal_mps2 : 0|16@1- (0.00195313,0) [-64|63.998] "m/s^2" Vector__XXX
#  SG_ Accel_lateral_mps2 : 16|16@1- (0.00195313,0) [-64|63.998] "m/s^2" Vector__XXX
#  SG_ Yaw_rate_degps : 32|16@1- (0.0078125,0) [-256|255.992] "deg/s" Vector__XXX