float32 rear_axle_trq         # Rear axle torque (-195 to 195 Nm)
float32 rear_axle_trq_request # Rear axle torque request (0-195 Nm)
float32 rear_axle_trq_max     # Maximum rear axle torque (0-195 Nm)

# BO_ 1314 VCU2AI_Drive_R: 6 VCU
#  SG_ REAR_AXLE_TRQ : 0|16@1- (0.1,0) [-195|195] "Nm" Vector__XXX
#  SG_ REAR_AXLE_TRQ_REQUEST : 16|16@1+ (0.1,0) [0|195] "Nm" Vector__XXX
#  SG_ REAR_AXLE_TRQ_MAX : 32|16@1+ (0.1,0) [0|195] "Nm" Vector__XXX