float32 front_axle_trq          # Front axle torque in Nm (-195 to 195)
float32 front_axle_trq_request  # Requested front axle torque in Nm (0 to 195)
float32 front_axle_trq_max      # Maximum front axle torque in Nm (0 to 195)

# BO_ 1313 VCU2AI_Drive_F: 6 VCU
#  SG_ FRONT_AXLE_TRQ : 0|16@1- (0.1,0) [-195|195] "Nm" Vector__XXX
#  SG_ FRONT_AXLE_TRQ_MAX : 32|16@1+ (0.1,0) [0|195] "Nm" Vector__XXX
#  SG_ FRONT_AXLE_TRQ_REQUEST : 16|16@1+ (0.1,0) [0|195] "Nm" Vector__XXX