float32 fl_wheel_speed  # Front Left wheel speed in rpm (0 to 1250)
float32 fr_wheel_speed  # Front Right wheel speed in rpm (0 to 1250)
float32 rl_wheel_speed  # Rear Left wheel speed in rpm (0 to 1250)
float32 rr_wheel_speed  # Rear Right wheel speed in rpm (0 to 1250)

# BO_ 1317 VCU2AI_Speeds: 8 VCU
#  SG_ FL_WHEEL_SPEED : 0|16@1+ (1,0) [0|1250] "rpm" Vector__XXX
#  SG_ FR_WHEEL_SPEED : 16|16@1+ (1,0) [0|1250] "rpm" Vector__XXX
#  SG_ RL_WHEEL_SPEED : 32|16@1+ (1,0) [0|1250] "rpm" Vector__XXX
#  SG_ RR_WHEEL_SPEED : 48|16@1+ (1,0) [0|1250] "rpm" Vector__XXX