uint16 fl_pulse_count # Front left wheel pulse count (0-65535)
uint16 fr_pulse_count # Front right wheel pulse count (0-65535)
uint16 rl_pulse_count # Rear left wheel pulse count (0-65535)
uint16 rr_pulse_count # Rear right wheel pulse count (0-65535)

# BO_ 1318 VCU2AI_Wheel_counts: 8 VCU
#  SG_ FL_PULSE_COUNT : 0|16@1+ (1,0) [0|65535] "" Vector__XXX
#  SG_ FR_PULSE_COUNT : 16|16@1+ (1,0) [0|65535] "" Vector__XXX
#  SG_ RL_PULSE_COUNT : 32|16@1+ (1,0) [0|65535] "" Vector__XXX
#  SG_ RR_PULSE_COUNT : 48|16@1+ (1,0) [0|65535] "" Vector__XXX